# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "/"
defaultContentLanguage = "en"

enableRobotsTXT = true
pagination.pagerSize = 20
summaryLength = 20

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "UA-35024589-1"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
